### ISSUE TITLE
表单校验问题

### ISSUE THREAD

**Issue by Deturium** [JasonQS/MSC-Joinus#1]
#### 截图

![tim 20180924143624](https://user-images.githubusercontent.com/19731097/45939728-4f261500-c007-11e8-9d0d-ee57139cf925.png)

#### 先说说问题
如果用户在面试【时间选择】的时候选择在某一栏选择不勾选任何时间段（而且是取消掉了默认勾选），那么提交表单的时候会获得一个写着 error 的 modal，而不是像类似没写电话时那样，告诉你电话是必须填写的

我看了下代码，只有后端校验，无论是提示信息（请填电话这种）还是出错信息（error）都是后端返回的，只是一个是 200 + 提示，另一个是 400

#### 解决问题的方法
问题很简单，顺着你现在的写法，就是当我时间选择没有填写正确的时候，不该是个 400 Bad Request ，应该是个 200 + 错误信息

#### 前端校验
讲实话我一般把这种规则比较细致的校验提示放前端做的，这样用户体验会更好
后端的校验反馈就比较笼统，如果出错就返回 错误 + 错误码，由前端来具体根据错误码显示具体信息
这样做的话在涉及国际化等问题的时候改进会更明显

**Comment by JasonQS** [comment]
已在后端把表单的时间参数设置为非必须的并且加了个没空的默认值, 感谢分享方案
